Handle 503 errors and throw an exception on failure
royendgel/django-backblazeb2-storage pull request #4
Opened 2016-10-22 22:10 UTC by AkeemMcLennon

2016-10-22 22:11 UTC, AkeemMcLennon commented on b2_storage/backblaze_b2.py
> +        # Status is 503: Service unavailable. Try again
It looks like sometimes servers go down (maybe related to DNS issues lately?) but the next request seems to route to a new server

2016-10-23 15:40 UTC, royendgel requested changes
Great! I
can you change line 65 into attempts += 1  ?

2016-10-29 03:53 UTC, AkeemMcLennon commented
Sorry for the late reply. This has been updated

2016-11-02 11:47 UTC, merged

2016-11-02 11:48 UTC, royendgel commented
Merged !